FROM golang:1.21.6 as build

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 go build ./cmd/dice-server

FROM scratch
WORKDIR /app

COPY --from=build /app/dice-server /app/dice-server
COPY --from=build /etc/passwd /etc/passwd

USER nobody

ENTRYPOINT ["/app/dice-server"]
